from project import list_files_pattern
from project import generate_header
import os


def test_list_files_pattern():
    """
    Returns a list of files located in a folder given by the first argument.
    The list includes the absolute path to each of the files.
    Each of the filenames includes the str "H2O_vs_days_all" specified by the second argument.
    The file in this example was previously generated by the program from the input dataset4.csv
    """
    assert (
        list_files_pattern("data/water_KF", "H2O_vs_days_all")[0]
        == "/workspaces/112820643/project/data/water_KF/H2O_vs_days_all_OilA.png"
    )


def test_generate_PDFreport():
    """
    Generates a PDF report including 1 or more figures generated from dataset4.csv
    In this test the program was run previously and the PDF report exists
    """
    entries = os.listdir(os.path.abspath(os.getcwd()))
    assert "report_H2O_vs_days_all.pdf" in entries

def test_generate_header():
    """
    Generates header for PDF report
    """
    assert generate_header("H2O_vs_days_all") == "Water content in ppm according to Karl-Fischer test, oil samples from wind turbines, all seasons"


